# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simA1 <- function(Q, D, X, Tx, inputA) {
    .Call(`_pr2ar_simA1`, Q, D, X, Tx, inputA)
}

simA2 <- function(Q, D, X, Tx, inputA) {
    .Call(`_pr2ar_simA2`, Q, D, X, Tx, inputA)
}

